trigger:
- main

variables:
  terraformVersion: '1.5.7'
  serviceConnection: 'test-connection02'
  workingDirectory: 'env/dev'

stages:

# ---------------- INIT + VALIDATE ----------------
- stage: Validate
  displayName: "Terraform Init & Validate"
  jobs:
  - job: Validate
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: $(terraformVersion)

    - task: TerraformTaskV4@4
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(workingDirectory)
        backendServiceArm: $(serviceConnection)
        backendAzureRmResourceGroupName: 'rg-terraform-state'
        backendAzureRmStorageAccountName: 'devstorage01234'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.terraform.tfstate'

    - task: TerraformTaskV4@4
      displayName: "Terraform Validate"
      inputs:
        provider: azurerm
        command: validate

# ---------------- PLAN ----------------
- stage: Plan
  displayName: "Terraform Plan"
  dependsOn: Validate

  jobs:
  - job: Plan
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: $(terraformVersion)

    - task: TerraformTaskV4@4
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(workingDirectory)
        backendServiceArm: $(serviceConnection)
        backendAzureRmResourceGroupName: 'rg-terraform-state'
        backendAzureRmStorageAccountName: 'devstorage01234'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.terraform.tfstate'

    - task: TerraformTaskV4@4
      displayName: "Terraform Plan"
      inputs:
        provider: azurerm
        command: plan
        environmentServiceNameAzureRM: $(serviceConnection)
        commandOptions: '-out=tfplan'

    - task: PublishPipelineArtifact@1
      displayName: Publish tfplan
      inputs:
        targetPath: '$(workingDir)/tfplan'
        artifact: tfplan

# ---------------- APPLY ---------------
- stage: Apply
  displayName: "Terraform Apply"
  dependsOn: Plan

  jobs:
  - job: Apply
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: $(terraformVersion)

    - task: TerraformTaskV4@4
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(workingDirectory)
        backendServiceArm: $(serviceConnection)
        backendAzureRmResourceGroupName: 'rg-terraform-state'
        backendAzureRmStorageAccountName: 'devstorage01234'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.terraform.tfstate'

    - task: DownloadPipelineArtifact@2
      displayName: Download tfplan
      inputs:
        artifact: tfplan
        path: $(workingDir)
    
    - task: TerraformTaskV4@4
      displayName: "Terraform apply"
      inputs:
        provider: azurerm
        command: apply
        environmentServiceNameAzureRM: $(serviceConnection)
        commandOptions: '-out=tfplan'

